# {name} - Bukkit Plugin configuration file
name: {name}
version: {plugin.version}
main: {bukkit.main.class}
author: Visual Illusions Entertainment
website: {wiki}

# Visual Illusions Specific Stuff
developers: {devs}
build.number: {build}
build.time: {build.time}
program.status: {program.status}
check.url: {version.check.url}
issues.url: {issues}
copyright.years: {copyright.years}
# -

commands:
  wallet:
    description: Wallet base command, Displays account balance.
    usage: /wallet [sub] [args]
    permission: dconomy.wallet.base
  wallet pay:
    description: Used to pay another user.
    usage: /wallet pay <amount> <user>
    permission: dconomy.wallet.pay
  wallet add:
    description: Adds money to a User's wallet
    usage: /wallet add <amount> <user>
    permission: dconomy.admin.wallet.add
  wallet remove:
    description: Removes money from a User's wallet
    usage: /wallet remove <amount> <user>
    permission: dconomy.admin.wallet.remove
  wallet set:
    description: Sets the money in a User's wallet
    usage: /wallet set <amount> <user>
    permission: dconomy.admin.wallet.set
  wallet reset:
    description: Resets the money in a User's wallet
    permission: dconomy.admin.wallet.reset
  wallet reload:
    description: Reloads a User's wallet from the datasource
    permissions: dconomy.admin.wallet.reload
  wallet lock:
    description: Locks/Unlocks a User's wallet
    permissions: dconomy.admin.wallet.lock
  dconomy:
    description: Displays build info about dConomy and a few other things.
    usage: /dconomy

permissions:
  dconomy.wallet.*:
    description: Gives access to all Wallet commands (except administration)
    default: op
    children:
      dconomy.wallet.base: true
      dconomy.wallet.pay: true
  dconomy.wallet.base:
    description: Give access to wallet base command.
    default: op
  dconomy.wallet.pay:
    description: Give access to wallet pay command.
    default: op
  dconomy.admin.wallet.*:
    description: Gives Admin rights to all dConomy Wallets
    default: op
    children:
      dconomy.admin.wallet.add: true
      dconomy.admin.wallet.remove: true
      dconomy.admin.wallet.set: true
      dconomy.admin.wallet.reset: true
      dconomy.admin.wallet.reload: true
      dconomy.admin.wallet.lock: true
  dconomy.admin.wallet.add:
    description: Gives rights to add money to a wallet
    default: op
  dconomy.admin.wallet.remove:
    description: Gives rights to remove money from a wallet
    default: op
  dconomy.admin.wallet.set:
    description: Gives rights to set the money in a wallet
    default: op
  dconomy.admin.wallet.reset:
    description: Gives rights to reset the money in a wallet
    default: op
  dconomy.admin.wallet.reload:
    description: Gives rights to reload a User's Wallet
    default: op
  dconomy.admin.wallet.lock:
    description: Gives rights to lock/unlock a User's Wallet
    default: op

# -
#  This file is part of {name}.
# -
#  Copyright © {copyright.years} Visual Illusions Entertainment.
# -
#  {name} is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# -
#  {name} is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
# -
#  You should have received a copy of the GNU General Public License along with {name}.
#  If not, see http://www.gnu.org/licenses/gpl.html
# -
